# Site settings
title: AdamForster
email: your-email@domain.com
url: https://example.github.io
description: "AdamForster, die Loesung für Ihr Fest. Sie können auf jeden Ansturm reagieren und den Umsatz steigern. Ihre Gaeste koennen immer bestellen und sehen, dass an ihrer Bestellung gearbeitet wird."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer:Service AdamForster

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
# Build settings
markdown: kramdown
permalink: pretty
